import 'package:ameen/utill/shared/constants_manager.dart';

class AssetsManager{
  static const String loginImage = '${AppConstants.imagePath}LoginPageImage.svg';
  static const String registerImage = '${AppConstants.imagePath}registerImage.svg';
  // static const String forgotPasswordImage = '${AppConstants.imagePath}forgotPasswordScreen.svg';
  static const String forgotPasswordImage = '${AppConstants.imagePath}forgotPasswordScreen.png';
  // static const String otpImage = '${AppConstants.imagePath}otpImage.svg';
  static const String otpImage = '${AppConstants.imagePath}OtpScreenImage.png';
  static const String logo = '${AppConstants.imagePath}appIcon.png';
  static const String languageImage = '${AppConstants.imagePath}languagePageImage.svg';
  static const String deliveryMotorcycle = '${AppConstants.imagePath}DeliveryMotorcycle.svg';
  static const String splashScreenImage = '${AppConstants.imagePath}splashScreen.png';
  // static const String arabic = '${AppConstants.imagePath}arabic.svg';
  static const String arabic = '${AppConstants.imagePath}arabic.png';
  static const String english = '${AppConstants.imagePath}english.svg';
  static const String home = '${AppConstants.imagePath}home.svg';
  static const String orders = '${AppConstants.imagePath}orders.svg';
  static const String wallet = '${AppConstants.imagePath}wallet.svg';
  static const String more = '${AppConstants.imagePath}more.svg';
  // static const String itemDelivery = '${AppConstants.imagePath}itemDelivery.svg';
  static const String itemDelivery = '${AppConstants.imagePath}itemDelivery.png';
  // static const String sahlRequest = '${AppConstants.imagePath}sahlRequest.svg';
  static const String sahlRequest = '${AppConstants.imagePath}sahlRequest.png';
  static const String addImage = '${AppConstants.imagePath}addPhoto.svg';
  static const String date = '${AppConstants.imagePath}date.svg';
  static const String creditCard = '${AppConstants.imagePath}creditCard.svg';
  static const String paymentSuccess = '${AppConstants.imagePath}paymentSuccessImage.svg';
  static const String paymentFailed = '${AppConstants.imagePath}paymentFailedImage.svg';
  static const String deliveredIcon = '${AppConstants.imagePath}deliveredIcon.svg';
  static const String itemIcon = '${AppConstants.imagePath}itemIcon.svg';
  static const String language = '${AppConstants.imagePath}globeIcon.svg';
  static const String myOrders = '${AppConstants.imagePath}numberedListIcon.svg';
  static const String profile = '${AppConstants.imagePath}personIcon.svg';
  static const String support = '${AppConstants.imagePath}supportIcon.svg';
  static const String termsAndConditions = '${AppConstants.imagePath}termsAndConditionsIcon.svg';
  static const String aboutUs = '${AppConstants.imagePath}aboutIcon.svg';
  static const String addImageIcon = '${AppConstants.imagePath}addImageIcon.svg';
  static const String whatsapp = '${AppConstants.imagePath}whatsapp.svg';
  static const String facebook = '${AppConstants.imagePath}facebook.svg';
  static const String instagram = '${AppConstants.imagePath}instagram.svg';
  static const String call = '${AppConstants.imagePath}call.svg';
  static const String sahlId = '${AppConstants.imagePath}sahlId.svg';
  static const String license = '${AppConstants.imagePath}license.svg';
  static const String userTopLoginIcon = '${AppConstants.imagePath}userTopLoginIcon.svg';
  static const String representativeLoginIcon = '${AppConstants.imagePath}representativeLoginImage.svg';
  static const String alertIcon = '${AppConstants.imagePath}alertIcon.svg';
}